[package]
name = "ecr-tag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.23"
inquire = "0.5.3"
rusoto_core = "0.48.0"
rusoto_ecr = "0.48.0"
tokio = "1.24.1"
